### ISSUE TITLE
Shard is not available

### ISSUE THREAD

**Issue by stephenpascoe** [stephenpascoe/esgf-pyclient#8]
I downloaded esgf-pyclient 0.1.1 from https://pypi.python.org/pypi/esgf-pyclient but now I get an error when trying to list download urls. This works with an older version of the library.

Program:

```
conn = SearchConnection('http://pcmdi9.llnl.gov/esg-search',distrib=True)

ctx = conn.new_context(experiment='piControl', time_frequency='day', variable='pr', ensemble='r1i1p1')
s = ctx.search()
for i in sorted(s, key=lambda pds: pds.dataset_id):
    publicationDataset, server = i.dataset_id.split('|')
    print publicationDataset, server, i.json['replica']

    searchContext = i.file_context()
    searchContext=searchContext.constrain(variable='pr')
    for j in searchContext.search():
    print j.download_url, j.checksum, j.checksum_type, j.size
```

Output and Error:

```
cmip5.output1.BCC.bcc-csm1-1-m.piControl.day.atmos.day.r1i1p1.v20120705 bcccsm.cma.gov.cn False Traceback (most recent call last):
  File "./compare1.py", line 26, in <module>
    for j in searchContext.search():
  File "/data/local/hadie/python/lib/python/esgf_pyclient-0.1.1-py2.6.egg/pyesgf/search/context.py", line 123, in search
    return ResultSet(sc)
  File "/data/local/hadie/python/lib/python/esgf_pyclient-0.1.1-py2.6.egg/pyesgf/search/results.py", line 40, in __init__
    self.__batch_cache[0] = self.__get_batch(0)
  File "/data/local/hadie/python/lib/python/esgf_pyclient-0.1.1-py2.6.egg/pyesgf/search/results.py", line 80, in __get_batch
    shards=self.context.shards)
  File "/data/local/hadie/python/lib/python/esgf_pyclient-0.1.1-py2.6.egg/pyesgf/search/connection.py", line 101, in send_search
    full_query = self._build_query(query_dict, limit, offset, shards)
  File "/data/local/hadie/python/lib/python/esgf_pyclient-0.1.1-py2.6.egg/pyesgf/search/connection.py", line 153, in _build_query
    raise EsgfSearchException('Shard %s is not available' % shard)
pyesgf.search.exceptions.EsgfSearchException: Shard pcmdi9.llnl.gov is not available
```

**Comment by stephenpascoe** [comment]
Confirmed.  Test created at commit 2e773a4

Something to do with the shard optimisation logic that was added between releases.

**Comment by stephenpascoe** [comment]
Fixed in devel c8d4e67.

The problem was local shards are listed as "localhost" in the json response but using their FQDN in the dataset metadata.

**Comment by stephenpascoe** [comment]
A new manifestation of this error.  Renamed ticket.

$ managecmip list -e historical -f mon -v tas
/data/local/hadie/python/lib/python/esgf_pyclient-0.1.1p1-py2.6.egg/pyesgf/search/connection.py:89: UserWarning: Old-style SearchContext URL specified.  In future please specify the URL excluding the "/search" endpoint.
  warnings.warn('Old-style SearchContext URL specified.  '
-------cmip5.output1.BCC.bcc-csm1-1-m.historical.mon.atmos.Amon.r1i1p1.v20120709
http://bcccsm.cma.gov.cn/thredds/fileServer/cmip5_data1/output/BCC/bcc-csm1-1-m/historical/mon/atmos/tas/r1i1p1/tas_Amon_bcc-csm1-1-m_historical_r1i1p1_185001-201212.nc 400655332 382.1Mb
-------cmip5.output1.BCC.bcc-csm1-1.historical.mon.atmos.Amon.r1i1p1.v1
http://bcccsm.cma.gov.cn/thredds/fileServer/cmip5_data/output/BCC/bcc-csm1-1/historical/mon/atmos/tas/r1i1p1/tas_Amon_bcc-csm1-1_historical_r1i1p1_185001-201212.nc 64153812 61.2Mb
-------cmip5.output1.BNU.BNU-ESM.historical.mon.atmos.Amon.r1i1p1.v20120510
http://esg.bnu.edu.cn/thredds/fileServer/cmip5/BNU/BNU-ESM/historical/mon/atmos/tas/r1i1p1/tas_Amon_BNU-ESM_historical_r1i1p1_185001-200512.nc 61398952 58.6Mb
-------cmip5.output1.CCCma.CanCM4.historical.mon.atmos.Amon.r1i1p1.v20120612
http://dapp2p.cccma.ec.gc.ca/thredds/fileServer/esg_dataroot/AR5/CMIP5/output/CCCma/CanCM4/historical/mon/atmos/tas/r1i1p1/tas_Amon_CanCM4_historical_r1i1p1_196101-200512.nc 17722576 16.9Mb
-------cmip5.output1.CCCma.CanESM2.historical.mon.atmos.Amon.r1i1p1.v20120718
http://dapp2p.cccma.ec.gc.ca/thredds/fileServer/esg_dataroot/AR5/CMIP5/output/CCCma/CanESM2/historical/mon/atmos/tas/r1i1p1/tas_Amon_CanESM2_historical_r1i1p1_185001-200512.nc 61401248 58.6Mb
-------cmip5.output1.CMCC.CMCC-CESM.historical.mon.atmos.Amon.r1i1p1.v20130416
Traceback (most recent call last):
  File "/home/h02/hadie/tr/trunk/managecmip/bin/managecmip", line 38, in <module>
    managecmip.run()
  File "/home/h02/hadie/tr/trunk/managecmip/src/managecmip.py", line 846, in run
    manager.list()
  File "/home/h02/hadie/tr/trunk/managecmip/src/managecmip.py", line 511, in list
    for j in esgf_search.getFileResult(i):
  File "/home/h02/hadie/tr/trunk/managecmip/src/managecmip.py", line 103, in getFileResult
    return self._search.getFileResult(datasetResult)
  File "/home/h02/hadie/tr/trunk/managecmip/src/managecmip.py", line 91, in getFileResult
    return sorted(searchContext.search(), key=lambda x: x.download_url)
  File "/data/local/hadie/python/lib/python/esgf_pyclient-0.1.1p1-py2.6.egg/pyesgf/search/context.py", line 123, in search
    return ResultSet(sc)
  File "/data/local/hadie/python/lib/python/esgf_pyclient-0.1.1p1-py2.6.egg/pyesgf/search/results.py", line 40, in __init__
    self.__batch_cache[0] = self.__get_batch(0)
  File "/data/local/hadie/python/lib/python/esgf_pyclient-0.1.1p1-py2.6.egg/pyesgf/search/results.py", line 80, in __get_batch
    shards=self.context.shards)
  File "/data/local/hadie/python/lib/python/esgf_pyclient-0.1.1p1-py2.6.egg/pyesgf/search/connection.py", line 102, in send_search
    full_query = self._build_query(query_dict, limit, offset, shards)
  File "/data/local/hadie/python/lib/python/esgf_pyclient-0.1.1p1-py2.6.egg/pyesgf/search/connection.py", line 154, in _build_query
    raise EsgfSearchException('Shard %s is not available' % shard)
pyesgf.search.exceptions.EsgfSearchException: Shard adm07.cmcc.it is not available

**Comment by stephenpascoe** [comment]
The shard optimisation code doesn't take account of replicated shards.  E.g. if a shard is replicated at PCMDI the dataset will say it is indexed in one place but the SearchConnection will be looking for it in a local replica.

We need a more forgiving algorithm which drops shard constraints if they don't match the available shards.
