### ISSUE TITLE
KeyError: 'shards'

### ISSUE THREAD

**Issue by stephenpascoe** [stephenpascoe/esgf-pyclient#9]
Affecting v0.1.1p1

$ managecmip list -e historical -f mon -v tas
/data/local/hadju/rels/2.0.2/lib/python2.6/site-packages/pyesgf/search/connection.py:89: UserWarning: Old-style SearchContext URL specified.  In future please specify the URL excluding the "/search" endpoint.
  warnings.warn('Old-style SearchContext URL specified.  '
-------cmip5.output1.BCC.bcc-csm1-1-m.historical.mon.atmos.Amon.r1i1p1.v20120709
Traceback (most recent call last):
  File "/data/local/hadju/rels/2.0.2/bin/managecmip", line 38, in <module>
    managecmip.run()
  File "/data/local/hadju/rels/2.0.2/lib/python2.6/site-packages/managecmip.py", line 846, in run
    manager.list()
  File "/data/local/hadju/rels/2.0.2/lib/python2.6/site-packages/managecmip.py", line 511, in list
    for j in esgf_search.getFileResult(i):
  File "/data/local/hadju/rels/2.0.2/lib/python2.6/site-packages/managecmip.py", line 103, in getFileResult
    return self._search.getFileResult(datasetResult)
  File "/data/local/hadju/rels/2.0.2/lib/python2.6/site-packages/managecmip.py", line 91, in getFileResult
    return sorted(searchContext.search(), key=lambda x: x.download_url)
  File "/data/local/hadju/rels/2.0.2/lib/python2.6/site-packages/pyesgf/search/context.py", line 123, in search
    return ResultSet(sc)
  File "/data/local/hadju/rels/2.0.2/lib/python2.6/site-packages/pyesgf/search/results.py", line 40, in __init__
    self.__batch_cache[0] = self.__get_batch(0)
  File "/data/local/hadju/rels/2.0.2/lib/python2.6/site-packages/pyesgf/search/results.py", line 80, in __get_batch
    shards=self.context.shards)
  File "/data/local/hadju/rels/2.0.2/lib/python2.6/site-packages/pyesgf/search/connection.py", line 102, in send_search
    full_query = self._build_query(query_dict, limit, offset, shards)
  File "/data/local/hadju/rels/2.0.2/lib/python2.6/site-packages/pyesgf/search/connection.py", line 149, in _build_query
    self._load_available_shards()
  File "/data/local/hadju/rels/2.0.2/lib/python2.6/site-packages/pyesgf/search/connection.py", line 189, in _load_available_shards
    shards = response_json['responseHeader']['params']['shards'].split(',')
KeyError: 'shards'

**Comment by stephenpascoe** [comment]
MOHC reports they can't reproduce either.  Marking as invalid.  It is probably an intermittent problem which the code should recover from more gracefully
